version: 0.2

phases:
  install:
    runtime-versions:
        python: 3.8
    commands:
        - echo Installing dependencies...
        - pip install -r requirements.txt
        - npm install
        - echo "Installing Docker Compose"
        - curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        - chmod +x /usr/local/bin/docker-compose
  pre_build:
    commands:
        - echo Building Docker images...
        - docker-compose build
  build:
    commands:
        - echo Build started on `date`
        - echo Building the Docker image...
        - docker-compose up -d
  post_build:
    commands:
        - echo Build completed on `date`