version: 0.2

# Define environment variables from AWS Parameter Store
env:
  parameter-store:
    OPENAI_API_KEY: ElijahChatGPTkey

phases:
  # Install the runtime dependencies, log into CodeArtifact for npm.
  install:
    runtime-versions:
      python: 3.10
      nodejs: 16
    commands:
      - cd app/frontend
      - aws codeartifact login --tool npm --repository npm-store --domain storygen --domain-owner 290481657399 --region us-east-2
      - cd ../..
  pre_build:
    commands:
    # Update package list, install Node.js dependencies.
      - echo Installing dependencies...
      - apt-get update
      - cd app/frontend && npm cache clean && npm install --omit=dev && chmod -R 755 node_modules && cd ../..
      - apt-get install -y jq

  build:
    commands:
    # Build the application.
      - echo Build started on `date`
      - echo Packaging the application...
      - cd app/frontend
      - npm run build
      - cd ../..

cache:
  paths:
    - "app/frontend/node_modules/**/*"
artifacts:
  files:
    - 'app/**/*'
  # discard-paths: yes
  name: storygen-artifact-$(date +%Y-%m-%d)