version: 0.2

env:
  parameter store:
    LOGIN: LOGIN
    HOST: SC-HOST
    Organization: SC-Organization
    Project: SC-Project
    CODEARTIFACT_AUTH_TOKEN: SC-CodeArtifact-Token
phases:
  install:
    runtime-versions:
        python: 3.8
    commands:
        - echo Installing dependencies...
        - pip install -r requirements.txt
        - npm install
        - echo "Installing Docker Compose"
        - curl -L "https://github.com/docker/compose/releases/download/2.15.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        - chmod +x /usr/local/bin/docker-compose
  pre_build:
    commands:
        - echo Building Docker images...
        - docker-compose build
  build:
    commands:
        - echo Build started on `date`
        - echo Building the Docker image...
        - docker-compose up -d
  post_build:
    commands:
        - echo Build completed on `date`
        - echo "Running docker services:"
        - docker-compose ps
        - echo "docker-compose logs:"
        - docker-compose logs