version: '3'
services:
  frontend:
  build: ./frontend
  volumes:
    - ./frontend:/usr/share/nginx/html
  ports:
    - 80:80
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - 5000:5000
    environment:
      - OPENAI_KEY=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