version: '3.8'

services:
  backend:
    container_name: story-backend
    build:
      context: ./app/backend
      dockerfile: Dockerfile
    ports:
      - '5001:5000'
    environment:
      - FLASK_ENV=${FLASK_ENV}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PROMPT_FILE_PATH=/app/main/prompt.json

  frontend:
    container_name: story-frontend
    build:
      context: ./app/frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development