version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - 80:80
  backend:
    build: ./backend
    volumes:
      - ./backend/src:/app
    ports:
      - 5001:5000
    env_file:
      - .env