version: '3'
services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - 80:80
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - 5001:5000
    env_file:
      - .env